package one.taya.gamelib.enums;

public enum AreaFlag {
    HEALTH, NO_HEALTH,
    FOOD, NO_FOOD,
    PVP, NO_PVP,
    BUILDING, NO_BUILDING,
    BREAKING, NO_BREAKING,
    DROPPING, NO_DROPPING,
    PICKUP, NO_PICKUP,
    DURABILITY_CHANGE, NO_DURABILITY_CHANGE,
    PLAYER_COLLISION, NO_PLAYER_COLLISION,
    INVENTORY_CHANGE, NO_INVENTORY_CHANGE,
    BLOCK_DROPS, NO_BLOCK_DROPS,
    MOB_SPAWNING, NO_MOB_SPAWNING
}